language: ruby
rvm:
- 2.2

install: gem install jekyll octopress-minify-html html-proofer
script: jekyll build && htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false